name: Deploy to Amazon ECS

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download image name artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: image-name
        path: .
    
    - name: Read image name from file
      id: read-image-name
      run: echo "IMAGE_NAME=$( cat image-name.txt)" >> $GITHUB_ENV

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker pull ${{ env.IMAGE_NAME }}
          sudo docker stop video-react || true
          sudo docker rm video-react || true
          sudo docker run -d --name video-react -p 3000:3000 ${{ env.IMAGE_NAME }}
