name: Docker Image CI and Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Set image name with date
      run: echo "IMAGE_NAME=bada308/video-react:$(date +%s)" >> $GITHUB_ENV

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile -t ${{ env.IMAGE_NAME }}
        docker push ${{ env.IMAGE_NAME }}

    - name: Save image name to file
      run: echo ${{ env.IMAGE_NAME }} > image-name.txt

    - name: Upload image name artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: image-name
        path: image-name.txt  # Adjusted path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download image name artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: image-name
    
    - name: Read image name from file
      id: read-image-name
      run: echo "IMAGE_NAME=$(cat image-name.txt)" >> $GITHUB_ENV

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker pull ${{ env.IMAGE_NAME }}
          sudo docker stop video-react || true
          sudo docker rm video-react || true
          sudo docker run -d --name video-react -p 3000:3000 ${{ env.IMAGE_NAME }}
