name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Set image name with date
      run: echo "IMAGE_NAME=bada308/video-react:$(date +%s)" >> $GITHUB_ENV

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile -t ${{ env.IMAGE_NAME }}
        docker push ${{ env.IMAGE_NAME }}

    - name: Save image name to file
      run: echo ${{ env.IMAGE_NAME }} >> image-name.txt

    - name: Upload image name artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: image-name
        path: image-name.txt
      
